<?php
namespace sky\yii\test;

use sky\yii\db\ActiveRecord;
use yii\db\ActiveQuery;
use Yii;

class Unit extends \Codeception\Test\Unit
{
    public function _before()
    {
        expect(YII_DEBUG)->true();
        Yii::$app->message->enable = false;
        parent::_before(); // TODO: Change the autogenerated stub
    }

    public static function queryLoop(ActiveQuery $query, $callback)
    {
        foreach ($query->all() as $model) {
            call_user_func($callback, $model);
        }
    }

    public static function basicModelTest(ActiveRecord $model, $instances = [])
    {
        expect($model)->isInstanceOf(ActiveRecord::class);
        foreach ($instances as $instance)
        {
            expect($model)->isInstanceOf($instance);
        }
        foreach ($model->attributes as $attribute => $value) {
            if ($model->isAttributeRequired($attribute)) {
                expect($value)->notEmpty();
            }
        }
    }
}