<?php
namespace sky\yii\httpclient;

class Client extends \yii\httpclient\Client
{
    public $requestConfig = [

    ];

    public function beforeSend($request)
    {
        parent::beforeSend($request); // TODO: Change the autogenerated stub
    }
}